### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by fredericseiler** [michaelarnauts/aiocomfoconnect#10]
Hi Michaël,

First of all, I wanted to thank you for what you've done with the library and HA integration. I have 0 issue sor far.

Now that I've flattered you, do you have any way to retrieve errors/alerts (like "RESISTANCE", "NOISE GUARD", "CHANGE FILTERS NOW"...) from the ComfoConnect LAN C ? It would be a nice addition to the library (and a super useful diagnostic entity in HA), if, of course, it's possible without too much work.

Thanks again!

**Comment by michaelarnauts** [comment]
Thanks!

I'm already reading out alarms, but I currently just output them as a warning in the logs. I'm not really sure how to expose them in Home Assistant. Alarms are things like overpressure (due to dirty filters), a warning to change the filters, ...

 See
* https://github.com/michaelarnauts/home-assistant-comfoconnect/blob/master/custom_components/comfoconnect/__init__.py#L165 (how the errors are logged in Home Assistant)
* https://github.com/michaelarnauts/aiocomfoconnect/blob/master/aiocomfoconnect/const.py#L62 (list of possible errors)

The resistance and noise guard are different things, and so far, I haven't found out yet how they are reported, or what they are called. This is also a thing that has been added to a newer firmware, and wasn't available when I initially reverse engineerd the protocol.

**Comment by fredericseiler** [comment]
> I'm already reading out alarms, but I currently just output them as a warning in the logs. I'm not really sure how to expose them in Home Assistant.

There's this new [Event entity](https://developers.home-assistant.io/docs/core/entity/event/) introduced in the 2023.8 release. Could this be of any help ?

> The resistance and noise guard are different things, and so far, I haven't found out yet how they are reported, or what they are called. This is also a thing that has been added to a newer firmware, and wasn't available when I initially reverse engineerd the protocol.

I currently have a Q350 ST with the noise and resistance (when I set the maximum speed) alerts active because I have to change the exhaust valve cone filters. Can I help you in any way to detect those alerts ?

**Comment by michaelarnauts** [comment]
The Event entity is to handle button presses (like a doorbell or another button). For alarms, I'm thinking Repairs might be better: https://developers.home-assistant.io/docs/core/platform/repairs/. But I still need to look at this further.

The "air flow reduced due to" "noise guard" or "resistance" could be a sensor. I just need to find how I can fetch them. I guess I'll have to dig trough the obfuscated Android code again :)

**Comment by michaelarnauts** [comment]
I've noticed that those constraints are available in PDO 230. I've added support for them here: https://github.com/michaelarnauts/aiocomfoconnect/pull/12

**Comment by michaelarnauts** [comment]
And it's been added to https://github.com/michaelarnauts/home-assistant-comfoconnect/commit/a30854685990c91176bbadc3499d2fed3ff06c61
